"""Simulation engine for Market Swarm.

Orchestrates agent evaluation of products using LLM-powered personas.
Industry-specific logic lives in industry_packs/ — this module is pack-agnostic.

Provides both sync (CLI) and async (API) execution paths:
- run_simulation()       — sequential, for CLI
- run_simulation_async() — parallel with semaphore, for API
"""

import asyncio
import json
import logging
import os
import re
from pathlib import Path
from typing import Optional

import anthropic
import openai
import yaml
from dotenv import load_dotenv
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from .models import AgentResponse, Product, SimulationConfig, SimulationResult
from .registry import get_pack

# Load .env from project root
load_dotenv(Path(__file__).resolve().parent.parent / ".env")

logger = logging.getLogger(__name__)

console = Console()

# EU AI Act Art. 50 — every simulation output carries this transparency notice.
DISCLAIMER = (
    "These results were generated by AI simulation and do not constitute "
    "empirical market research. All persona reactions are fictional and do "
    "not represent the actual positions of any company."
)

NO_API_KEY_MESSAGE = (
    "No LLM API key configured.\n"
    "Set one of: GEMINI_API_KEY, ANTHROPIC_API_KEY, OPENROUTER_API_KEY, "
    "OPENAI_API_KEY (see .env.example).\n"
    "Or run an offline demo without any key: MARKET_SWARM_MOCK=1"
)


def mock_enabled() -> bool:
    """Whether mock mode is active (offline demo, no LLM calls)."""
    return os.environ.get("MARKET_SWARM_MOCK", "").lower() in ("1", "true", "yes")


def _mock_evaluation(persona, product: Product) -> dict:
    """Produce a deterministic, plausible evaluation without an LLM call.

    Used for offline demos, CI, and regenerating dashboard sample data.
    Scores are derived from a stable hash of persona + product so repeated
    runs give identical output.
    """
    seed = sum(ord(c) for c in f"{persona.name}:{product.name}")
    score = round(4.0 + (seed % 55) / 10.0, 1)  # 4.0 .. 9.4
    would_list = score >= 6.0
    criteria = persona.evaluation_criteria or ["overall_fit"]
    lead = criteria[seed % len(criteria)].replace("_", " ")

    if would_list:
        feedback = (
            f"{product.name} is a credible fit for my segment — "
            f"{lead} is where it wins. I would trial it under conditions."
        )
    else:
        feedback = f"{product.name} does not clear my bar on {lead}; as offered, I would pass."

    return {
        "score": score,
        "would_list": would_list,
        "key_feedback": feedback,
        "objections": [
            f"Needs stronger evidence on {criteria[(seed + 1) % len(criteria)].replace('_', ' ')}",
        ],
        "suggestions": [
            f"Sharpen the positioning on {lead} before launch",
        ],
        "detailed_reasoning": (
            "Mock evaluation (MARKET_SWARM_MOCK=1): deterministic sample output "
            "for demos — no LLM was called."
        ),
    }


def load_product(path: str) -> tuple[Product, SimulationConfig]:
    """Load product definition from YAML file."""
    with open(path) as f:
        data = yaml.safe_load(f)

    product_data = data["product"]
    product_type = product_data.get("product_type", "fmcg")

    pack = get_pack(product_type)

    if pack.attributes_model:
        product_data["attributes"] = pack.attributes_model(**product_data.get("attributes", {}))
    if pack.pricing_model:
        product_data["pricing"] = pack.pricing_model(**product_data.get("pricing", {}))
    if pack.competitor_model:
        product_data["competitors"] = [
            pack.competitor_model(**c) for c in product_data.get("competitors", [])
        ]

    product = Product(**product_data)
    sim_config = SimulationConfig(**data.get("simulation", {}))
    return product, sim_config


def build_evaluation_prompt(product: Product, focus_areas: list[str]) -> str:
    """Build the product evaluation prompt, dispatching via pack registry."""
    pack = get_pack(product.product_type)
    if pack.prompt_builder is None:
        raise ValueError(f"Pack '{product.product_type}' has no prompt builder configured.")
    return pack.prompt_builder.build_evaluation_prompt(product, focus_areas)


def _get_client():
    """Get the appropriate LLM client based on available API keys."""
    gemini_key = os.environ.get("GEMINI_API_KEY")
    if gemini_key:
        return "gemini", openai.OpenAI(
            base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
            api_key=gemini_key,
        )
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY")
    if anthropic_key:
        return "anthropic", anthropic.Anthropic()
    openrouter_key = os.environ.get("OPENROUTER_API_KEY")
    if openrouter_key:
        return "openrouter", openai.OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=openrouter_key,
        )
    openai_key = os.environ.get("OPENAI_API_KEY")
    if openai_key:
        return "openai", openai.OpenAI()
    raise RuntimeError(NO_API_KEY_MESSAGE)


# Map short model names to provider-specific model IDs
OPENROUTER_MODELS = {
    "claude-sonnet-4-5": "anthropic/claude-sonnet-4-5",
    "claude-sonnet-4-5-20250514": "anthropic/claude-sonnet-4-5-20250514",
    "gpt-4o": "openai/gpt-4o",
    "gpt-4o-mini": "openai/gpt-4o-mini",
}

GEMINI_DEFAULT_MODEL = "gemini-2.5-flash"

# Default concurrency for async simulation (respects LLM rate limits)
DEFAULT_MAX_CONCURRENT = 5

# Retry config for transient API errors
MAX_RETRIES = 3
RETRY_BASE_DELAY = 2.0  # seconds, doubles each attempt


def _get_async_client():
    """Get an async LLM client. Same priority chain as _get_client()."""
    gemini_key = os.environ.get("GEMINI_API_KEY")
    if gemini_key:
        return "gemini", openai.AsyncOpenAI(
            base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
            api_key=gemini_key,
        )
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY")
    if anthropic_key:
        return "anthropic", anthropic.AsyncAnthropic()
    openrouter_key = os.environ.get("OPENROUTER_API_KEY")
    if openrouter_key:
        return "openrouter", openai.AsyncOpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=openrouter_key,
        )
    openai_key = os.environ.get("OPENAI_API_KEY")
    if openai_key:
        return "openai", openai.AsyncOpenAI()
    raise RuntimeError(NO_API_KEY_MESSAGE)


def _resolve_model(backend: str, model: str) -> tuple[str, int]:
    """Resolve model name and token limit for a given backend."""
    if backend == "gemini":
        return GEMINI_DEFAULT_MODEL, 8192
    elif backend == "openrouter":
        return OPENROUTER_MODELS.get(model, model), 1024
    else:
        return model, 1024


def _parse_llm_response(text: str) -> dict:
    """Parse JSON from LLM response text using 4-strategy fallback.

    Shared by both sync and async evaluation paths.
    """
    # Extract from markdown code blocks
    if "```json" in text:
        text = text.split("```json")[1].split("```")[0]
    elif "```" in text:
        text = text.split("```")[1].split("```")[0]

    text = text.strip()
    data = None

    # Strategy 1: Direct parse
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        pass

    # Strategy 2: Find outermost { ... } block
    if data is None:
        start = text.find("{")
        end = text.rfind("}")
        if start >= 0 and end > start:
            try:
                data = json.loads(text[start : end + 1])
            except json.JSONDecodeError:
                pass

    # Strategy 3: Fix common LLM JSON issues (unescaped newlines in strings)
    if data is None:
        start = text.find("{")
        end = text.rfind("}")
        if start >= 0 and end > start:
            candidate = text[start : end + 1]
            fixed = re.sub(
                r'(?<=: ")(.*?)(?="[,\n\r\t ]*["}])',
                lambda m: m.group(0).replace("\n", " ").replace("\r", ""),
                candidate,
                flags=re.DOTALL,
            )
            try:
                data = json.loads(fixed)
            except json.JSONDecodeError:
                pass

    # Strategy 4: Line-by-line reconstruction
    if data is None:
        start = text.find("{")
        end = text.rfind("}")
        if start >= 0 and end > start:
            lines = text[start : end + 1].split("\n")
            merged = []
            for line in lines:
                stripped = line.strip()
                if (
                    merged
                    and stripped
                    and not stripped.startswith('"')
                    and not stripped.startswith("}")
                    and not stripped.startswith("]")
                    and not stripped.startswith("[")
                ):
                    merged[-1] = merged[-1].rstrip() + " " + stripped
                else:
                    merged.append(line)
            try:
                data = json.loads("\n".join(merged))
            except json.JSONDecodeError:
                raise json.JSONDecodeError("All 4 JSON extraction strategies failed", text, 0)

    if data is None:
        raise json.JSONDecodeError("No JSON found in response", text, 0)

    return data


def _build_agent_response(persona, data: dict) -> AgentResponse:
    """Construct AgentResponse from parsed JSON + persona metadata."""
    agent_type = getattr(persona.type, "value", persona.type)
    return AgentResponse(
        agent_name=persona.name,
        agent_type=agent_type,
        retailer=persona.retailer,
        **data,
    )


def _aggregate_results(product: Product, responses: list[AgentResponse]) -> SimulationResult:
    """Aggregate individual agent responses into a SimulationResult."""
    result = SimulationResult(
        product=product,
        responses=responses,
        avg_score=(sum(r.score for r in responses) / len(responses) if responses else 0),
        listing_rate=(
            sum(1 for r in responses if r.would_list) / len(responses) if responses else 0
        ),
        disclaimer=DISCLAIMER,
    )

    all_objections = [obj for r in responses for obj in r.objections]
    result.top_objections = list(dict.fromkeys(all_objections))[:10]

    all_suggestions = [s for r in responses for s in r.suggestions]
    result.top_suggestions = list(dict.fromkeys(all_suggestions))[:10]

    channel_map: dict[str, list[float]] = {}
    for r in responses:
        channel = r.retailer or r.agent_type
        channel_map.setdefault(channel, []).append(r.score)
    result.channel_scores = {k: sum(v) / len(v) for k, v in channel_map.items()}

    return result


def evaluate_with_agent(
    persona,
    product: Product,
    focus_areas: list[str],
    model: str = "claude-sonnet-4-5",
) -> AgentResponse:
    """Run a single agent evaluation (synchronous — for CLI use)."""
    if mock_enabled():
        return _build_agent_response(persona, _mock_evaluation(persona, product))

    backend, client = _get_client()
    evaluation_prompt = build_evaluation_prompt(product, focus_areas)
    resolved_model, token_limit = _resolve_model(backend, model)

    if backend == "anthropic":
        response = client.messages.create(
            model=model,
            max_tokens=1024,
            system=persona.to_system_message(),
            messages=[{"role": "user", "content": evaluation_prompt}],
        )
        text = response.content[0].text
    else:
        response = client.chat.completions.create(
            model=resolved_model,
            max_tokens=token_limit,
            messages=[
                {"role": "system", "content": persona.to_system_message()},
                {"role": "user", "content": evaluation_prompt},
            ],
        )
        text = response.choices[0].message.content

    data = _parse_llm_response(text)
    return _build_agent_response(persona, data)


def run_simulation(
    product_path: str,
    model: str = "claude-sonnet-4-5",
    verbose: bool = True,
    pack_override: str | None = None,
) -> SimulationResult:
    """Run a full market simulation (synchronous — for CLI use)."""
    product, config = load_product(product_path)

    product_type = pack_override or product.product_type
    pack = get_pack(product_type)
    personas_to_run = pack.personas
    total = len(personas_to_run)

    if verbose:
        panel_info = pack.prompt_builder.build_panel_info(product)
        console.print(
            Panel(
                f"[bold]{product.name}[/bold] ({product.brand})\n"
                f"Category: {product.category} / {product.subcategory}\n"
                f"Pricing: {panel_info.get('pricing_line', 'n/a')}\n"
                f"Agents: {total}",
                title=panel_info.get("title", "Market Swarm Simulation"),
                border_style="cyan",
            )
        )

    responses: list[AgentResponse] = []

    for i, persona in enumerate(personas_to_run, 1):
        if verbose:
            console.print(f"  [{i}/{total}] {persona.name} ({persona.type})...", end=" ")

        try:
            response = evaluate_with_agent(
                persona=persona,
                product=product,
                focus_areas=config.focus_areas,
                model=model,
            )
            responses.append(response)

            if verbose:
                emoji = "\u2705" if response.would_list else "\u274c"
                console.print(f"{emoji} {response.score}/10 \u2014 {response.key_feedback}")

        except Exception as e:
            if verbose:
                console.print(f"[red]ERROR: {e}[/red]")

    return _aggregate_results(product, responses)


# ---------------------------------------------------------------------------
# Async execution path (for API / parallel evaluation)
# ---------------------------------------------------------------------------


async def evaluate_with_agent_async(
    persona,
    product: Product,
    focus_areas: list[str],
    model: str = "claude-sonnet-4-5",
    *,
    semaphore: asyncio.Semaphore | None = None,
) -> AgentResponse:
    """Run a single agent evaluation (async — for API use).

    Includes retry with exponential backoff on transient errors (429, 5xx).
    """
    if mock_enabled():
        return _build_agent_response(persona, _mock_evaluation(persona, product))

    backend, client = _get_async_client()
    evaluation_prompt = build_evaluation_prompt(product, focus_areas)
    resolved_model, token_limit = _resolve_model(backend, model)

    async def _call_llm() -> str:
        if backend == "anthropic":
            response = await client.messages.create(
                model=model,
                max_tokens=1024,
                system=persona.to_system_message(),
                messages=[{"role": "user", "content": evaluation_prompt}],
            )
            return response.content[0].text
        else:
            response = await client.chat.completions.create(
                model=resolved_model,
                max_tokens=token_limit,
                messages=[
                    {"role": "system", "content": persona.to_system_message()},
                    {"role": "user", "content": evaluation_prompt},
                ],
            )
            return response.choices[0].message.content

    # Retry loop with backoff
    last_error = None
    for attempt in range(MAX_RETRIES):
        try:
            if semaphore:
                async with semaphore:
                    text = await _call_llm()
            else:
                text = await _call_llm()

            data = _parse_llm_response(text)
            return _build_agent_response(persona, data)

        except (anthropic.RateLimitError, openai.RateLimitError) as e:
            last_error = e
            delay = RETRY_BASE_DELAY * (2**attempt)
            logger.warning(
                "Rate limited on %s (attempt %d/%d), retrying in %.1fs",
                persona.name,
                attempt + 1,
                MAX_RETRIES,
                delay,
            )
            await asyncio.sleep(delay)

        except (anthropic.APIStatusError, openai.APIStatusError) as e:
            status = getattr(e, "status_code", 0)
            if status >= 500:
                last_error = e
                delay = RETRY_BASE_DELAY * (2**attempt)
                logger.warning(
                    "Server error %d on %s (attempt %d/%d), retrying in %.1fs",
                    status,
                    persona.name,
                    attempt + 1,
                    MAX_RETRIES,
                    delay,
                )
                await asyncio.sleep(delay)
            else:
                raise  # 4xx (except 429) = don't retry

    raise RuntimeError(f"Failed after {MAX_RETRIES} retries for {persona.name}: {last_error}")


async def run_simulation_async(
    product_path: str,
    model: str = "claude-sonnet-4-5",
    pack_override: str | None = None,
    max_concurrent: int = DEFAULT_MAX_CONCURRENT,
    on_progress: Optional[callable] = None,
) -> SimulationResult:
    """Run a full market simulation with parallel LLM calls.

    Args:
        product_path: Path to product YAML file.
        model: LLM model name.
        pack_override: Force a specific industry pack.
        max_concurrent: Max parallel LLM calls (default 5).
        on_progress: Optional callback(completed: int, total: int) for progress tracking.
    """
    product, config = load_product(product_path)

    product_type = pack_override or product.product_type
    pack = get_pack(product_type)
    personas_to_run = pack.personas
    total = len(personas_to_run)
    semaphore = asyncio.Semaphore(max_concurrent)

    completed_count = 0

    async def _eval_one(persona) -> AgentResponse | None:
        nonlocal completed_count
        try:
            result = await evaluate_with_agent_async(
                persona=persona,
                product=product,
                focus_areas=config.focus_areas,
                model=model,
                semaphore=semaphore,
            )
            completed_count += 1
            if on_progress:
                on_progress(completed_count, total)
            return result
        except Exception as e:
            logger.error("Agent %s failed: %s", persona.name, e)
            completed_count += 1
            if on_progress:
                on_progress(completed_count, total)
            return None

    results = await asyncio.gather(*[_eval_one(p) for p in personas_to_run])
    responses = [r for r in results if r is not None]

    return _aggregate_results(product, responses)


def print_results(result: SimulationResult) -> None:
    """Print simulation results in a formatted table."""
    pack = get_pack(result.product.product_type)
    panel_info = pack.prompt_builder.build_panel_info(result.product)
    rate_label = panel_info.get("rate_label", "Listing Rate")

    console.print()
    console.print(
        Panel(
            f"Product: [bold]{result.product.name}[/bold] ({result.product.brand})\n"
            f"Agents: {len(result.responses)} | Avg Score: {result.avg_score:.1f}/10 | "
            f"{rate_label}: {result.listing_rate:.0%}",
            title="Market Swarm Results",
            border_style="green"
            if result.avg_score >= 7
            else "yellow"
            if result.avg_score >= 5
            else "red",
        )
    )

    # Channel breakdown
    table = Table(title="Agent Scores")
    table.add_column("Agent", style="cyan")
    table.add_column("Score", justify="right")
    table.add_column("Key Feedback")

    for r in result.responses:
        channel = r.retailer or r.agent_type
        emoji = "\u2705" if r.would_list else "\u274c"
        score_style = "green" if r.score >= 7 else "yellow" if r.score >= 5 else "red"
        table.add_row(
            f"{emoji} {r.agent_name} ({channel})",
            f"[{score_style}]{r.score:.1f}[/{score_style}]",
            r.key_feedback,
        )

    console.print(table)

    # Top objections
    if result.top_objections:
        console.print("\n[bold red]Top Objections:[/bold red]")
        for i, obj in enumerate(result.top_objections[:5], 1):
            console.print(f"  {i}. {obj}")

    # Top suggestions
    if result.top_suggestions:
        console.print("\n[bold green]Top Suggestions:[/bold green]")
        for i, sug in enumerate(result.top_suggestions[:5], 1):
            console.print(f"  {i}. {sug}")

    # EU AI Act Art. 50 — Transparency disclaimer
    console.print(f"\n[dim]Note: {DISCLAIMER}[/dim]")
