"""PDF and PPTX export for Market Swarm simulation results.

Generates professional reports from SimulationResult data.
EU AI Act Art. 50 disclaimer is included in all exports.
"""

from io import BytesIO
from typing import Any

from fpdf import FPDF
from pptx import Presentation
from pptx.util import Inches, Pt


def export_pdf(result_data: dict) -> bytes:
    """Generate a PDF report from simulation result data.

    Returns PDF as bytes (write to file or stream to HTTP response).
    """
    product = result_data.get("product", {})
    responses = result_data.get("responses", [])

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 12, "Market Swarm", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, "LLM-powered market simulation", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(8)

    # Product info
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
        0,
        10,
        f"{product.get('name', '?')} ({product.get('brand', '?')})",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.set_font("Helvetica", "", 10)
    cat = product.get("category", "")
    sub = product.get("subcategory", "")
    pdf.cell(
        0,
        6,
        f"Category: {cat}{f' / {sub}' if sub else ''}",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(4)

    # Score summary
    avg = result_data.get("avg_score", 0)
    rate = result_data.get("listing_rate", 0)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Results Overview", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Average score: {avg:.1f} / 10", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Recommendation rate: {rate:.0%}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Agents: {len(responses)}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # Agent scores table
    if responses:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Agent Evaluations", new_x="LMARGIN", new_y="NEXT")

        # Table header
        pdf.set_font("Helvetica", "B", 9)
        col_widths = [55, 20, 15, 100]
        headers = ["Agent", "Score", "", "Key Feedback"]
        for w, h in zip(col_widths, headers):
            pdf.cell(w, 7, h, border=1)
        pdf.ln()

        # Table rows
        pdf.set_font("Helvetica", "", 8)
        for r in responses:
            name = r.get("agent_name", "?")
            retailer = r.get("retailer")
            if retailer:
                name = f"{name} ({retailer})"
            score = r.get("score", 0)
            icon = "Y" if r.get("would_list") else "N"
            feedback = r.get("key_feedback", "")
            # Truncate feedback to fit
            if len(feedback) > 80:
                feedback = feedback[:77] + "..."

            pdf.cell(col_widths[0], 6, _safe(name[:40]), border=1)
            pdf.cell(col_widths[1], 6, f"{score:.1f}", border=1, align="R")
            pdf.cell(col_widths[2], 6, icon, border=1, align="C")
            pdf.cell(col_widths[3], 6, _safe(feedback), border=1)
            pdf.ln()

    pdf.ln(6)
    pdf.set_x(pdf.l_margin)  # Reset x-position after table

    # Objections
    objections = result_data.get("top_objections", [])
    if objections:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Top Objections", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        for i, obj in enumerate(objections[:5], 1):
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 5, f"{i}. {_safe(obj)}")
        pdf.ln(4)

    # Suggestions
    suggestions = result_data.get("top_suggestions", [])
    if suggestions:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Top Suggestions", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        for i, sug in enumerate(suggestions[:5], 1):
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 5, f"{i}. {_safe(sug)}")
        pdf.ln(4)

    # Disclaimer
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(120, 120, 120)
    disclaimer = result_data.get(
        "disclaimer",
        "These results were generated by AI simulation and do not constitute "
        "empirical market research.",
    )
    pdf.multi_cell(0, 4, _safe(disclaimer))
    pdf.set_text_color(0, 0, 0)

    return pdf.output()


def export_pptx(result_data: dict) -> bytes:
    """Generate a PPTX presentation from simulation result data.

    Returns PPTX as bytes.
    """
    product = result_data.get("product", {})
    responses = result_data.get("responses", [])
    avg = result_data.get("avg_score", 0)
    rate = result_data.get("listing_rate", 0)

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # --- Slide 1: Title ---
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank
    _add_text(
        slide,
        "Market Swarm",
        Inches(0.8),
        Inches(1),
        Inches(11),
        Inches(1.2),
        size=36,
        bold=True,
    )
    _add_text(
        slide,
        f"{product.get('name', '?')} ({product.get('brand', '?')})",
        Inches(0.8),
        Inches(2.2),
        Inches(11),
        Inches(0.8),
        size=24,
    )
    cat = product.get("category", "")
    sub = product.get("subcategory", "")
    _add_text(
        slide,
        f"Category: {cat}{f' / {sub}' if sub else ''}",
        Inches(0.8),
        Inches(3.0),
        Inches(11),
        Inches(0.6),
        size=14,
        color=(100, 100, 100),
    )

    # Score summary
    _add_text(
        slide,
        f"Score: {avg:.1f}/10  |  Recommendation: {rate:.0%}  |  {len(responses)} agents",
        Inches(0.8),
        Inches(4.2),
        Inches(11),
        Inches(0.8),
        size=20,
        bold=True,
    )

    # --- Slide 2: Agent Scores ---
    slide2 = prs.slides.add_slide(prs.slide_layouts[6])
    _add_text(
        slide2,
        "Agent Evaluations",
        Inches(0.8),
        Inches(0.4),
        Inches(11),
        Inches(0.8),
        size=24,
        bold=True,
    )

    y = Inches(1.4)
    for r in responses[:12]:  # max 12 per slide
        name = r.get("agent_name", "?")
        retailer = r.get("retailer")
        label = f"{name} ({retailer})" if retailer else name
        score = r.get("score", 0)
        icon = "\u2713" if r.get("would_list") else "\u2717"
        feedback = r.get("key_feedback", "")
        if len(feedback) > 60:
            feedback = feedback[:57] + "..."

        _add_text(slide2, f"{icon} {label}", Inches(0.8), y, Inches(3.5), Inches(0.4), size=11)
        _add_text(
            slide2,
            f"{score:.1f}",
            Inches(4.5),
            y,
            Inches(0.8),
            Inches(0.4),
            size=11,
            bold=True,
        )
        _add_text(
            slide2,
            feedback,
            Inches(5.5),
            y,
            Inches(7),
            Inches(0.4),
            size=10,
            color=(80, 80, 80),
        )
        y += Inches(0.45)

    # --- Slide 3: Insights ---
    slide3 = prs.slides.add_slide(prs.slide_layouts[6])
    _add_text(
        slide3,
        "Objections & Suggestions",
        Inches(0.8),
        Inches(0.4),
        Inches(11),
        Inches(0.8),
        size=24,
        bold=True,
    )

    objections = result_data.get("top_objections", [])
    suggestions = result_data.get("top_suggestions", [])

    y = Inches(1.4)
    if objections:
        _add_text(
            slide3,
            "Top Objections",
            Inches(0.8),
            y,
            Inches(5),
            Inches(0.5),
            size=14,
            bold=True,
            color=(220, 50, 50),
        )
        y += Inches(0.5)
        for obj in objections[:5]:
            _add_text(slide3, f"\u2022 {obj}", Inches(1.0), y, Inches(5), Inches(0.4), size=11)
            y += Inches(0.4)

    y += Inches(0.3)
    if suggestions:
        _add_text(
            slide3,
            "Top Suggestions",
            Inches(0.8),
            y,
            Inches(5),
            Inches(0.5),
            size=14,
            bold=True,
            color=(16, 185, 129),
        )
        y += Inches(0.5)
        for sug in suggestions[:5]:
            _add_text(slide3, f"\u2022 {sug}", Inches(1.0), y, Inches(5), Inches(0.4), size=11)
            y += Inches(0.4)

    # Disclaimer on last slide
    disclaimer = result_data.get("disclaimer", "AI simulation — not empirical market research.")
    _add_text(
        slide3,
        disclaimer,
        Inches(0.8),
        Inches(6.5),
        Inches(11),
        Inches(0.5),
        size=8,
        color=(150, 150, 150),
    )

    buf = BytesIO()
    prs.save(buf)
    return buf.getvalue()


# --- Helpers ---


def _safe(text: str) -> str:
    """Replace characters that fpdf2 can't encode in latin-1."""
    result = (
        text.replace("\u20ac", "EUR")
        .replace("\u2013", "-")
        .replace("\u2014", "-")
        .replace("\u2018", "'")
        .replace("\u2019", "'")
        .replace("\u201c", '"')
        .replace("\u201d", '"')
        .replace("\u2026", "...")
        .replace("\u00e4", "ae")
        .replace("\u00f6", "oe")
        .replace("\u00fc", "ue")
        .replace("\u00c4", "Ae")
        .replace("\u00d6", "Oe")
        .replace("\u00dc", "Ue")
        .replace("\u00df", "ss")
        .replace("\u2022", "-")
        .replace("\u2713", "Y")
        .replace("\u2717", "N")
    )
    # Strip any remaining non-latin-1 characters
    return result.encode("latin-1", errors="replace").decode("latin-1")


def _add_text(
    slide: Any,
    text: str,
    left,
    top,
    width,
    height,
    size: int = 12,
    bold: bool = False,
    color: tuple | None = None,
) -> None:
    """Add a text box to a PPTX slide."""
    from pptx.dml.color import RGBColor

    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = Pt(size)
    p.font.bold = bold
    if color:
        p.font.color.rgb = RGBColor(*color)
